export const ELECTIONLIST_REQUEST = 'ELECTIONLIST_REQUEST'
export const ELECTIONLIST_SUCCESS = 'ELECTIONLIST_SUCCESS'
export const ELECTIONLIST_FAIL = 'ELECTIONLIST_FAIL'

export const MY_ELECTION_REQUEST = 'MY_ELECTION_REQUEST'
export const MY_ELECTION_SUCCESS = 'MY_ELECTION_SUCCESS'
export const MY_ELECTION_FAIL = 'MY_ELECTION_FAIL'

export const ELECTIONLIST_CHECK = 'ELECTIONLIST_CHECK '
export const ELECTIONLIST_CHECK_OUT = 'ELECTIONLIST_CHECK_OUT '