export const HASHLIST_SUM_REQUEST = 'HASHLIST_SUM_REQUEST'
export const HASHLIST_SUM_SUCCESS = 'HASHLIST_SUM_SUCCESS'
export const HASHLIST_SUM_FAIL = 'HASHLIST_SUM_FAIL'

export const MY_HASHLIST_REQUEST = 'MY_HASHLIST_REQUEST'
export const MY_HASHLIST_SUCCESS = 'MY_HASHLIST_SUCCESS'
export const MY_HASHLIST_FAIL = 'MY_HASHLIST_FAIL'

export const ALL_HASHLIST_REQUEST = 'ALL_HASHLIST_REQUEST'
export const ALL_HASHLIST_SUCCESS = 'ALL_HASHLIST_SUCCESS'
export const ALL_HASHLIST_FAIL = 'ALL_HASHLIST_FAIL'