export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL' 

export const USER_SENDMAIL_REQUEST = 'USER_CERTIFICATION_REQUEST'
export const USER_SENDMAIL_SUCCESS = 'USER_CERTIFICATION_SUCCESS'
export const USER_SENDMAIL_FAIL = 'USER_CERTIFICATION_FAIL' 

export const USER_CERTIFICATION_REQUEST = 'USER_CERTIFICATION_REQUEST'
export const USER_CERTIFICATION_SUCCESS = 'USER_CERTIFICATION_SUCCESS'
export const USER_CERTIFICATION_FAIL = 'USER_CERTIFICATION_FAIL' 

export const USER_RESET_CERTIFICATION_NUMBER_CHECK = 'USER_RESET_CERTIFICATION_NUMBER_CHECK'

export const USER_ERROR_SUCCESS_RESET = 'USER_ERROR_SUCCESS_RESET'